import { CandidateProfile } from '../types';

export const mockCandidates: CandidateProfile[] = [
  {
    id: "profile-1",
    fileName: "Nguyen_Minh_Anh_CV.pdf",
    appliedDate: "2026-05-15",
    week: "W20",
    position: "Senior Frontend Engineer",
    name: "Nguyễn Minh Anh",
    cvLink: "https://scan-cv-storage.s3.ap-southeast-1.amazonaws.com/cvs/Nguyen_Minh_Anh_CV.pdf",
    email: "minhanh.nguyen@gmail.com",
    phone: "+84 912 345 678",
    sourceDetail: "LinkedIn Outreach",
    level: "Senior",
    yearOfBirth: "1994",
    educationalLevel: "Bachelor of Science",
    university: "Hanoi University of Science and Technology",
    expectSalary: "45,000,000 VND",
    branch: "Hanoi HQ",
    hmReview: "Strong candidate with solid Next.js experience. Handled large scale SaaS dashboards and state performance. Impressive communication and system design skills.",
    hmResult: "Pass to R1",
    taOwner: "Hoàng Thu Trang",
    rate: "4.5 / 5",
    interviewer: "Phạm Minh Đức (Tech Lead) & Nguyễn Văn A (EM)",
    status: "Offer Accepted",
    r1Date: "2026-05-18",
    r2Date: "2026-05-22",
    offerDate: "2026-05-24",
    acceptedOfferDate: "2026-05-25",
    onboardDate: "2026-06-15",
    timeToHire: "10 days",
    declineReason: "",
    month: "May",
    rawResponse: {}
  },
  {
    id: "profile-2",
    fileName: "Tran_Thi_Mai_ProductManager.pdf",
    appliedDate: "2026-05-18",
    week: "W21",
    position: "Middle Product Manager",
    name: "Trần Thị Mai",
    cvLink: "https://scan-cv-storage.s3.ap-southeast-1.amazonaws.com/cvs/Tran_Thi_Mai_ProductManager.pdf",
    email: "mai.tranthi@outlook.com",
    phone: "+84 988 777 666",
    sourceDetail: "Referral (Nam Le)",
    level: "Middle",
    yearOfBirth: "1997",
    educationalLevel: "Master of Business Administration",
    university: "Foreign Trade University (FTU)",
    expectSalary: "35,000,000 VND",
    branch: "Ho Chi Minh Office",
    hmReview: "Good project delivery background. Has driven ecommerce expansion. Strong analytical skills, needs to drill down on technical product spec definitions.",
    hmResult: "Pass to R2",
    taOwner: "Lê Thanh Tùng",
    rate: "4.0 / 5",
    interviewer: "Trần Hùng (CPO) & Nguyễn Hương (HRD)",
    status: "Negotiating Offer",
    r1Date: "2026-05-20",
    r2Date: "2026-05-25",
    offerDate: "2026-05-27",
    acceptedOfferDate: "",
    onboardDate: "",
    timeToHire: "9 days",
    declineReason: "",
    month: "May",
    rawResponse: {}
  },
  {
    id: "profile-3",
    fileName: "Le_Hoang_Nam_DevOps.pdf",
    appliedDate: "2026-05-20",
    week: "W21",
    position: "DevOps Engineer / Tech Lead",
    name: "Lê Hoàng Nam",
    cvLink: "https://scan-cv-storage.s3.ap-southeast-1.amazonaws.com/cvs/Le_Hoang_Nam_DevOps.pdf",
    email: "nam.lehoang@techcorp.io",
    phone: "+84 909 111 222",
    sourceDetail: "TopCV",
    level: "Lead / Principal",
    yearOfBirth: "1991",
    educationalLevel: "Engineer's Degree in Computer Science",
    university: "Vietnam National University, HCM (UIT)",
    expectSalary: "60,000,000 VND",
    branch: "Remote (Vietnam)",
    hmReview: "Exceptional cloud engineering background. Specialized in AWS, Kubernetes, and automated CI/CD pipelines. Strong understanding of cost-optimization and high-availability architecture.",
    hmResult: "Failed R1",
    taOwner: "Hoàng Thu Trang",
    rate: "2.8 / 5",
    interviewer: "Đinh Xuân Trường (Cloud Architect)",
    status: "Rejected",
    r1Date: "2026-05-24",
    r2Date: "",
    offerDate: "",
    acceptedOfferDate: "",
    onboardDate: "",
    timeToHire: "4 days",
    declineReason: "Expected salary is significantly higher than branch budget, and failed complex live networking challenge",
    month: "May",
    rawResponse: {}
  }
];
